version: '3'

networks:
  file-hosting:
    driver: bridge

volumes:
  db-data:
    driver: local
  minio-data:
    driver: local

services:
  postgres:
    image: 'postgres:15.1-alpine'
    container_name: FH-DB
    ports:
      - "5435:5432"
    env_file:
      - .env
    networks:
      - file-hosting
    volumes:
      - db-data:/var/lid/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: FH-MINIO
    environment:
      MINIO_ROOT_USER: ${MINIO_USERNAME}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    command: server ~/minio --console-address :9090
    ports:
      - '9090:9090'
      - '9009:9000'
    volumes:
      - minio-data:/minio