spring:
  config:
    import: optional:file:.env[.properties]
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 0
  datasource:
    url: jdbc:postgresql://${HOST}/${POSTGRES_DB}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none
minio:
  url: ${MINIO_URL}
  username: ${MINIO_USERNAME}
  password: ${MINIO_SECRET_KEY}
jwt:
  secret: ${JWT_SECRET}
  access: ${JWT_ACCESS_EXPIRATION}
  refresh: ${JWT_REFRESH_EXPIRATION}